on:
    push:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4 ##code generated
            - name: Run tests           ## tests
              run: pytest

