on:
    push:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4 ## code generated

            - name: Setup Python           ## python
              uses: actions/setup-python@v5
              with:
                python-version: 3.12

            - name: Install Req           ## Req
              run: pip install -r requirements.txt

            - name: Run tests           ## tests
              run: pytest

    build-and-push:
        needs: [test]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4 ## code generated

            - name: Build and Push Docker Container          ## python
              run: |
                docker build -t tarekelshourbagy22/devops .
                    echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u tarekelshourbagy22 --password-stdin
                    docker push tarekelshourbagy22/devops




